[phases.setup]
nixPkgs = ['python39']

[phases.install]
cmd = 'pip install -r requirements.txt'

[phases.build]
cmd = 'echo "Build completed"'

[start]
cmd = 'uvicorn backend_api:app --host 0.0.0.0 --port $PORT' 